### ISSUE TITLE
[meom code clinic] general structure (having a readme, a licence, contributing guide, etc)

### ISSUE THREAD

**Issue by rcaneill** [morays-community/.github#2]
This issue is open for the MEOM internal code clinic / review process

**Comment by rcaneill** [comment]
### general structure (having a readme, a licence, contributing guide, etc)



- [ ] Package has a README.md file in the root directory.
- [ ] Package documentation is easy to find.
- [ ] The package is easy to install
- [ ] **License:** Does the repository contain a plain-text LICENSE or COPYING file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
- [ ] **Metadata** including author(s), author e-mail(s), a url, and any other relevant metadata e.g., in a `pyproject.toml` file or elsewhere.

**Comment by rcaneill** [comment]
this issue can apply to the whole organisation

**Comment by auraoupa** [comment]
> ### general structure (having a readme, a licence, contributing guide, etc)

> * [x]  Package has a README.md file in the root directory.
A change in a sentence is proposed

> * [x]  Package documentation is easy to find.

It could be even better with a badge on top on the readme (generated by readthedoc)

> * [x]  The package is easy to install

This is not a package but really a documentation, so nothing has to be installed

> * [ ]  **License:** Does the repository contain a plain-text LICENSE or COPYING file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

There are no license at all, we suggest [this license](https://github.com/ige-calcul/public-docs/blob/main/LICENSE)

> * [x]  **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

> * []  **Metadata** including author(s), author e-mail(s), a url, and any other relevant metadata e.g., in a `pyproject.toml` file or elsewhere.

No except in the documentation itself, in which there only the name

**Comment by alexis-barge** [comment]
done
