### ISSUE TITLE
[meom code clinic] Documentation

### ISSUE THREAD

**Issue by rcaneill** [morays-community/.github#4]
This issue is open for the MEOM internal code clinic / review process

**Comment by rcaneill** [comment]
### Documentation

- [ ] **Vignette(s)** / **Example usage:** demonstrating major functionality (ideally to solve real-world analysis problems).
- [ ] **Function Documentation:** for functions used in the examples.

**Comment by rcaneill** [comment]
@alexis-barge could you add a link to the specific doc you’ld like us to review?

**Comment by alexis-barge** [comment]
https://morays-doc.readthedocs.io/en/latest/index.html
