### ISSUE TITLE
[meom code clinic] README

### ISSUE THREAD

**Issue by rcaneill** [morays-community/.github#5]
This issue is open for the MEOM internal code clinic / review process

**Comment by rcaneill** [comment]
The README should include:

- [ ] The package name
- [ ] Short description of package goals.
- [ ] Package installation instructions
    - [ ] Brief demonstration of package usage (as it makes sense - links to vignettes could also suffice here if package description is clear)
- [ ] Link to your documentation website.
- [ ] If applicable, how the package compares to other similar packages and/or how it relates to other packages in the scientific ecosystem.
- [ ] Citation information

**Comment by rcaneill** [comment]
@alexis-barge could you add the link to the readme you’ld like us to review (e.g. the dino example?)

**Comment by alexis-barge** [comment]
NEMO-DINO : https://github.com/morays-community/NEMO-DINO
NEMO-MLE_Fluxes (for a second README example) : https://github.com/morays-community/NEMO-MLE_Fluxes

**Comment by lesommer** [comment]
@noemieplanat and I suggest to reorganize the organization README with the following sections. 

—
## What is morays organization   
Morays organization provides a collection of example deployments of the eophis package in ocean models. It provides a solution for sharing the model experiments across centers. Our ambition is to offer a plateform for fostering exchanges amongst eophis users.  

## How morays works 
Start with a short descrtiption of eophis (as for the instance the onde in the “strategy section). 

Explain eophis can be deployed in different models. Explain that we store  in this organisation the deployment in ocean models (NEMO and CROCO  so far )

Explain that each deployment is documented in a self contained separate GH repo. Provide links to the list of repos

## How to reproduce moray experiments : 

Explain that each repo provides all the material for reproducing an experiment : Code, model configuration

Instruction  for deployment can be found here  : https://morays-doc.readthedocs.io/en/latest/getting_started.html

## How to contribute 
The current scetion of ok. May be switching the two bullets, with these titles : 
 - Modify an existing deployment  
- Create a new deployment  

## How to cite 
- use the doi of each repo . 
- provide citation instruction for the eophis library
