### ISSUE TITLE
[meom-code-clinic] Add generic schematic to explain the workflow of a Morays experiment

### ISSUE THREAD

**Issue by HugoJacq** [morays-community/.github#7]
Looking at the 'Overview' page of the documentation, a picture with the different layers of a Morays experiments could be good. Something like the picture from the 'Getting Started' but with generic names ocean model,oasis coupler, Eophis, ML python model.

**Comment by HugoJacq** [comment]
And also maybe add on the picture where XIOS is used, and by what

**Comment by alexis-barge** [comment]
done
